services:
  postgres:
    container_name: postgres-prod
  motis:
    container_name: motis-prod
  backend:
    container_name: backend-prod
  nginx:
    container_name: nginx-prod
    volumes:
      - ./config/nginx/nginx.prod.conf:/etc/nginx/conf.d/default.conf
  prometheus:
    container_name: prometheus-prod
  grafana:
    container_name: grafana-prod
  node-exporter:
    container_name: node-exporter-prod
