services:
  postgres:
    container_name: postgres-local
    ports:
      - "5432:5432"
  motis-import:
    volumes:
      - ./config/motis/input:/input
      - ./config/motis/config.yml:/config.yml
      - ./motis-data:/data
  motis:
    container_name: motis-local
    volumes:
      - ./motis-data:/data
    ports:
      - "3000:3000"
