services:
  postgres:
    container_name: postgres-prod
    ports:
      - "5432:5432"
  motis:
    container_name: motis-prod
  backend:
    container_name: backend-prod
  backend-canary:
    container_name: backend-canary-prod
  nginx:
    container_name: nginx-prod
    volumes:
      - /srv/meetlink/nginx/conf:/etc/nginx/conf.d:ro
  prometheus:
    container_name: prometheus-prod
  grafana:
    container_name: grafana-prod
  node-exporter:
    container_name: node-exporter-prod
  cadvisor:
    container_name: cadvisor-prod
