services:
  postgres:
    container_name: meetlink-db-prod
    restart: unless-stopped
  app:
    container_name: meetlink-app-prod
    restart: unless-stopped
  nginx:
    restart: unless-stopped
    volumes:
      - ./config/nginx.prod.conf:/etc/nginx/conf.d/default.conf
