services:
  postgres:
    container_name: postgres-dev
    ports:
      - "5432:5432"
  motis:
    container_name: motis-dev
  backend:
    container_name: backend-dev
  nginx:
    container_name: nginx-dev
    volumes:
      - ./config/nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf
  prometheus:
    container_name: prometheus-dev
  grafana:
    container_name: grafana-dev
  node-exporter:
    container_name: node-exporter-dev
  cadvisor:
    container_name: cadvisor_dev

