services:
  postgres:
    container_name: postgres-local
    ports:
      - "5432:5432"
  motis-import:
    volumes:
      - ./config/motis/input:/input
      - ./motis-data:/data
  motis:
    container_name: motis-local
    volumes:
      - ./motis-data:/data
    ports:
      - "3000:3000"
  prometheus:
    container_name: prometheus-local
  grafana:
    container_name: grafana-local
    ports:
      - "3001:3000"
  node-exporter:
    container_name: node-exporter-local
