spring:
  application:
    name: meetlink
  web:
    resources:
      add-mappings: false
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100
        order_inserts: true
        order_updates: true
  lifecycle:
    timeout-per-shutdown-phase: 30s
server:
  forward-headers-strategy: framework
  shutdown: graceful
cors:
  allowed-origins: >
    http://localhost:5173
motis:
  base-url: http://motis:3000
kakao:
  api-key: ${KAKAO_API_KEY}
sentry:
  dsn: ${SENTRY_DSN}
  environment: ${SPRING_PROFILES_ACTIVE}
  logs:
    enabled: true
  send-default-pii: true
  tags:
    deployment: ${DEPLOYMENT_TYPE}
management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    tags:
      application: ${spring.application.name}
      deployment: ${DEPLOYMENT_TYPE}
