spring:
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    org.hibernate.SQL: info
    com.greedy.meetlink: debug
sentry:
  traces-sample-rate: 0.05
cors:
  allowed-origins: >
    http://localhost:5173,
    https://dev.meetlink.now
