spring:
  jpa:
    hibernate:
      ddl-auto: update
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
logging:
  level:
    root: warn
    org.hibernate.SQL: warn
    com.greedy.meetlink: info
sentry:
  traces-sample-rate: 0.2
cors:
  allowed-origins: >
    https://meetlink.now
