#!/bin/sh

PROJECT_ROOT="$(git rev-parse --show-toplevel)"

cd "$PROJECT_ROOT" || exit 1

echo "Running spotlessApply on staged files..."

# Windows Support
if [[ "$OS" == "Windows_NT" ]]; then
  ./gradlew.bat spotlessApply
else
  ./gradlew spotlessApply
fi

if [ $? -ne 0 ]; then
  echo "spotlessApply failed. Commit aborted."
  exit 1
fi

git diff --name-only --cached | xargs git add
echo "Successfully executed spotlessApply on staged files."
exit 0
