#!/bin/sh

PROJECT_ROOT="$(git rev-parse --show-toplevel)"
cd "$PROJECT_ROOT" || exit 1

STAGED_FILES=$(git diff --cached --name-only)

if [ -z "$STAGED_FILES" ]; then
  exit 0
fi

echo "Running spotlessApply on staged files..."

# Windows Support
if [[ "$OS" == "Windows_NT" ]]; then
  ./gradlew.bat spotlessApply
else
  ./gradlew spotlessApply
fi

if [ $? -ne 0 ]; then
  echo "spotlessApply failed. Commit aborted."
  exit 1
fi

echo "$STAGED_FILES" | xargs git add
echo "Successfully executed spotlessApply on staged files."
exit 0
